torchrun  --master-port 1111 --nproc_per_node=2 main.py \
    --model_path_prefix /mnt/buffer/wutong \
    --target DeepSeek-R1-Distill-Qwen-32B \
    --model_type qwen2_5 \
    --ckpt_path /mnt/buffer/wutong/adapter_ckpts_R1_qwen2_5_32b/kv_lr_0.005/checkpoint-200 \
    --prefill_len 4096 \
    --retrival_max_budget 4096 \
    --gen_len 102400 \
    --gamma 4 \
    --min_p 0.1 \
    --temperature 1.0 \
    --tree_decoding \
    --ngram_topk 20 \
    --penalty 1.2 \
    --penalty_length 1024 \
    --prompt_id 0 \
    --tp_size 2
